// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.lipabusinesslib;

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the detils of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.ptr.ByReference
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    @JvmField var capacity: Int = 0
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : RustBuffer(), Structure.ByValue
    class ByReference : RustBuffer(), Structure.ByReference

    companion object {
        internal fun alloc(size: Int = 0) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_lipabusinesslib_f273_rustbuffer_alloc(size, status).also {
                if(it.data == null) {
                   throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
               }
            }
        }

        internal fun free(buf: RustBuffer.ByValue) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_lipabusinesslib_f273_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setInt(0, value.capacity)
        pointer.setInt(4, value.len)
        pointer.setPointer(8, value.data)
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): Int

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity.toLong()).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
@Structure.FieldOrder("code", "error_buf")
internal open class RustCallStatus : Structure() {
    @JvmField var code: Int = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    fun isSuccess(): Boolean {
        return code == 0
    }

    fun isError(): Boolean {
        return code == 1
    }

    fun isPanic(): Boolean {
        return code == 2
    }
}

class InternalException(message: String) : Exception(message)

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: Exception> rustCallWithError(errorHandler: CallStatusErrorHandler<E>, callback: (RustCallStatus) -> U): U {
    var status = RustCallStatus();
    val return_value = callback(status)
    if (status.isSuccess()) {
        return return_value
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
object NullCallStatusErrorHandler: CallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> rustCall(callback: (RustCallStatus) -> U): U {
    return rustCallWithError(NullCallStatusErrorHandler, callback);
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_lipabusinesslib"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface _UniFFILib : Library {
    companion object {
        internal val INSTANCE: _UniFFILib by lazy {
            loadIndirect<_UniFFILib>(componentName = "lipabusinesslib")
            
        }
    }

    fun ffi_lipabusinesslib_f273_Wallet_object_free(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun lipabusinesslib_f273_Wallet_new(`config`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): Pointer

    fun lipabusinesslib_f273_Wallet_sync(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun lipabusinesslib_f273_Wallet_get_balance(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_Wallet_get_addr(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_Wallet_parse_address(`ptr`: Pointer,`address`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_Wallet_prepare_drain_tx(`ptr`: Pointer,`addr`: RustBuffer.ByValue,`confirmInBlocks`: Int,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_Wallet_sign_and_broadcast_tx(`ptr`: Pointer,`txBlob`: RustBuffer.ByValue,`spendDescriptor`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_Wallet_get_tx_status(`ptr`: Pointer,`txid`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_Wallet_get_spending_txs(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_Wallet_is_drain_tx_affordable(`ptr`: Pointer,`confirmInBlocks`: Int,
    _uniffi_out_err: RustCallStatus
    ): Byte

    fun ffi_lipabusinesslib_f273_Auth_object_free(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun lipabusinesslib_f273_Auth_new(`backendUrl`: RustBuffer.ByValue,`authLevel`: RustBuffer.ByValue,`walletKeypair`: RustBuffer.ByValue,`authKeypair`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): Pointer

    fun lipabusinesslib_f273_Auth_query_token(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_Auth_get_wallet_pubkey_id(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_init_native_logger_once(`minLevel`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun lipabusinesslib_f273_generate_mnemonic(
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_derive_keys(`network`: RustBuffer.ByValue,`mnemonicString`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_sign(`message`: RustBuffer.ByValue,`privateKey`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipabusinesslib_f273_generate_keypair(
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ffi_lipabusinesslib_f273_rustbuffer_alloc(`size`: Int,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ffi_lipabusinesslib_f273_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ffi_lipabusinesslib_f273_rustbuffer_free(`buf`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun ffi_lipabusinesslib_f273_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Int,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    
}

// Public interface members begin here.


public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len)
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteArr = value.toByteArray(Charsets.UTF_8)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteArr.size)
        rbuf.asByteBuffer()!!.put(byteArr)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    override fun allocationSize(value: String): Int {
        val sizeForLength = 4
        val sizeForString = value.length * 3
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteArr = value.toByteArray(Charsets.UTF_8)
        buf.putInt(byteArr.size)
        buf.put(byteArr)
    }
}


public object FfiConverterTimestamp: FfiConverterRustBuffer<java.time.Instant> {
    override fun read(buf: ByteBuffer): java.time.Instant {
        val seconds = buf.getLong()
        // Type mismatch (should be u32) but we check for overflow/underflow below
        val nanoseconds = buf.getInt().toLong()
        if (nanoseconds < 0) {
            throw java.time.DateTimeException("Instant nanoseconds exceed minimum or maximum supported by uniffi")
        }
        if (seconds >= 0) {
            return java.time.Instant.EPOCH.plus(java.time.Duration.ofSeconds(seconds, nanoseconds))
        } else {
            return java.time.Instant.EPOCH.minus(java.time.Duration.ofSeconds(-seconds, nanoseconds))
        }
    }

    // 8 bytes for seconds, 4 bytes for nanoseconds
    override fun allocationSize(value: java.time.Instant) = 12

    override fun write(value: java.time.Instant, buf: ByteBuffer) {
        var epochOffset = java.time.Duration.between(java.time.Instant.EPOCH, value)

        var sign = 1
        if (epochOffset.isNegative()) {
            sign = -1
            epochOffset = epochOffset.negated()
        }

        if (epochOffset.nano < 0) {
            // Java docs provide guarantee that nano will always be positive, so this should be impossible
            // See: https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html
            throw IllegalArgumentException("Invalid timestamp, nano value must be non-negative")
        }

        buf.putLong(sign * epochOffset.seconds)
        // Type mismatch (should be u32) but since values will always be between 0 and 999,999,999 it should be OK
        buf.putInt(epochOffset.nano)
    }
}


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

// The base class for all UniFFI Object types.
//
// This class provides core operations for working with the Rust `Arc<T>` pointer to
// the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// the Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each `FFIObject` instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an `FFIObject` is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an `FFIObject` instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so will
//     leak the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each `FFIObject` an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// In the future we may be able to replace some of this with automatic finalization logic, such as using
// the new "Cleaner" functionaility in Java 9. The above scheme has been designed to work even if `destroy` is
// invoked by garbage-collection machinery rather than by calling code (which by the way, it's apparently also
// possible for the JVM to finalize an object while there is an in-flight call to one of its methods [1],
// so there would still be some complexity here).
//
// Sigh...all of this for want of a robust finalization mechanism.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//
abstract class FFIObject(
    protected val pointer: Pointer
): Disposable, AutoCloseable {

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    open protected fun freeRustArcPtr() {
        // To be overridden in subclasses.
    }

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                this.freeRustArcPtr()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.pointer)
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                this.freeRustArcPtr()
            }
        }
    }
}

public interface AuthInterface {
    
    @Throws(AuthException::class)
    fun `queryToken`(): String
    
    fun `getWalletPubkeyId`(): String?
    
}

class Auth(
    pointer: Pointer
) : FFIObject(pointer), AuthInterface {
    constructor(`backendUrl`: String, `authLevel`: AuthLevel, `walletKeypair`: KeyPair, `authKeypair`: KeyPair) :
        this(
    rustCallWithError(AuthException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Auth_new(FfiConverterString.lower(`backendUrl`), FfiConverterTypeAuthLevel.lower(`authLevel`), FfiConverterTypeKeyPair.lower(`walletKeypair`), FfiConverterTypeKeyPair.lower(`authKeypair`), _status)
})

    /**
     * Disconnect the object from the underlying Rust object.
     *
     * It can be called more than once, but once called, interacting with the object
     * causes an `IllegalStateException`.
     *
     * Clients **must** call this method once done with the object, or cause a memory leak.
     */
    override protected fun freeRustArcPtr() {
        rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_lipabusinesslib_f273_Auth_object_free(this.pointer, status)
        }
    }

    
    @Throws(AuthException::class)override fun `queryToken`(): String =
        callWithPointer {
    rustCallWithError(AuthException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Auth_query_token(it,  _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    override fun `getWalletPubkeyId`(): String? =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Auth_get_wallet_pubkey_id(it,  _status)
}
        }.let {
            FfiConverterOptionalString.lift(it)
        }
    

    
}

public object FfiConverterTypeAuth: FfiConverter<Auth, Pointer> {
    override fun lower(value: Auth): Pointer = value.callWithPointer { it }

    override fun lift(value: Pointer): Auth {
        return Auth(value)
    }

    override fun read(buf: ByteBuffer): Auth {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: Auth) = 8

    override fun write(value: Auth, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}




public interface WalletInterface {
    
    @Throws(WalletException::class)
    fun `sync`()
    
    @Throws(WalletException::class)
    fun `getBalance`(): Balance
    
    @Throws(WalletException::class)
    fun `getAddr`(): String
    
    @Throws(AddressParsingException::class)
    fun `parseAddress`(`address`: String): String
    
    @Throws(WalletException::class)
    fun `prepareDrainTx`(`addr`: String, `confirmInBlocks`: UInt): Tx
    
    @Throws(WalletException::class)
    fun `signAndBroadcastTx`(`txBlob`: List<UByte>, `spendDescriptor`: String): TxDetails
    
    @Throws(WalletException::class)
    fun `getTxStatus`(`txid`: String): TxStatus
    
    @Throws(WalletException::class)
    fun `getSpendingTxs`(): List<TxDetails>
    
    @Throws(WalletException::class)
    fun `isDrainTxAffordable`(`confirmInBlocks`: UInt): Boolean
    
}

class Wallet(
    pointer: Pointer
) : FFIObject(pointer), WalletInterface {
    constructor(`config`: Config) :
        this(
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Wallet_new(FfiConverterTypeConfig.lower(`config`), _status)
})

    /**
     * Disconnect the object from the underlying Rust object.
     *
     * It can be called more than once, but once called, interacting with the object
     * causes an `IllegalStateException`.
     *
     * Clients **must** call this method once done with the object, or cause a memory leak.
     */
    override protected fun freeRustArcPtr() {
        rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_lipabusinesslib_f273_Wallet_object_free(this.pointer, status)
        }
    }

    
    @Throws(WalletException::class)override fun `sync`() =
        callWithPointer {
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Wallet_sync(it,  _status)
}
        }
    
    
    @Throws(WalletException::class)override fun `getBalance`(): Balance =
        callWithPointer {
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Wallet_get_balance(it,  _status)
}
        }.let {
            FfiConverterTypeBalance.lift(it)
        }
    
    @Throws(WalletException::class)override fun `getAddr`(): String =
        callWithPointer {
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Wallet_get_addr(it,  _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    @Throws(AddressParsingException::class)override fun `parseAddress`(`address`: String): String =
        callWithPointer {
    rustCallWithError(AddressParsingException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Wallet_parse_address(it, FfiConverterString.lower(`address`),  _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    @Throws(WalletException::class)override fun `prepareDrainTx`(`addr`: String, `confirmInBlocks`: UInt): Tx =
        callWithPointer {
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Wallet_prepare_drain_tx(it, FfiConverterString.lower(`addr`), FfiConverterUInt.lower(`confirmInBlocks`),  _status)
}
        }.let {
            FfiConverterTypeTx.lift(it)
        }
    
    @Throws(WalletException::class)override fun `signAndBroadcastTx`(`txBlob`: List<UByte>, `spendDescriptor`: String): TxDetails =
        callWithPointer {
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Wallet_sign_and_broadcast_tx(it, FfiConverterSequenceUByte.lower(`txBlob`), FfiConverterString.lower(`spendDescriptor`),  _status)
}
        }.let {
            FfiConverterTypeTxDetails.lift(it)
        }
    
    @Throws(WalletException::class)override fun `getTxStatus`(`txid`: String): TxStatus =
        callWithPointer {
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Wallet_get_tx_status(it, FfiConverterString.lower(`txid`),  _status)
}
        }.let {
            FfiConverterTypeTxStatus.lift(it)
        }
    
    @Throws(WalletException::class)override fun `getSpendingTxs`(): List<TxDetails> =
        callWithPointer {
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Wallet_get_spending_txs(it,  _status)
}
        }.let {
            FfiConverterSequenceTypeTxDetails.lift(it)
        }
    
    @Throws(WalletException::class)override fun `isDrainTxAffordable`(`confirmInBlocks`: UInt): Boolean =
        callWithPointer {
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_Wallet_is_drain_tx_affordable(it, FfiConverterUInt.lower(`confirmInBlocks`),  _status)
}
        }.let {
            FfiConverterBoolean.lift(it)
        }
    

    
}

public object FfiConverterTypeWallet: FfiConverter<Wallet, Pointer> {
    override fun lower(value: Wallet): Pointer = value.callWithPointer { it }

    override fun lift(value: Pointer): Wallet {
        return Wallet(value)
    }

    override fun read(buf: ByteBuffer): Wallet {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: Wallet) = 8

    override fun write(value: Wallet, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}




data class Balance (
    var `confirmed`: ULong, 
    var `trustedPending`: ULong, 
    var `untrustedPending`: ULong, 
    var `immature`: ULong
) {
    
}

public object FfiConverterTypeBalance: FfiConverterRustBuffer<Balance> {
    override fun read(buf: ByteBuffer): Balance {
        return Balance(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: Balance) = (
            FfiConverterULong.allocationSize(value.`confirmed`) +
            FfiConverterULong.allocationSize(value.`trustedPending`) +
            FfiConverterULong.allocationSize(value.`untrustedPending`) +
            FfiConverterULong.allocationSize(value.`immature`)
    )

    override fun write(value: Balance, buf: ByteBuffer) {
            FfiConverterULong.write(value.`confirmed`, buf)
            FfiConverterULong.write(value.`trustedPending`, buf)
            FfiConverterULong.write(value.`untrustedPending`, buf)
            FfiConverterULong.write(value.`immature`, buf)
    }
}




data class Config (
    var `electrumUrl`: String, 
    var `walletDbPath`: String, 
    var `network`: Network, 
    var `watchDescriptor`: String
) {
    
}

public object FfiConverterTypeConfig: FfiConverterRustBuffer<Config> {
    override fun read(buf: ByteBuffer): Config {
        return Config(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeNetwork.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: Config) = (
            FfiConverterString.allocationSize(value.`electrumUrl`) +
            FfiConverterString.allocationSize(value.`walletDbPath`) +
            FfiConverterTypeNetwork.allocationSize(value.`network`) +
            FfiConverterString.allocationSize(value.`watchDescriptor`)
    )

    override fun write(value: Config, buf: ByteBuffer) {
            FfiConverterString.write(value.`electrumUrl`, buf)
            FfiConverterString.write(value.`walletDbPath`, buf)
            FfiConverterTypeNetwork.write(value.`network`, buf)
            FfiConverterString.write(value.`watchDescriptor`, buf)
    }
}




data class Descriptors (
    var `spendDescriptor`: String, 
    var `watchDescriptor`: String
) {
    
}

public object FfiConverterTypeDescriptors: FfiConverterRustBuffer<Descriptors> {
    override fun read(buf: ByteBuffer): Descriptors {
        return Descriptors(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: Descriptors) = (
            FfiConverterString.allocationSize(value.`spendDescriptor`) +
            FfiConverterString.allocationSize(value.`watchDescriptor`)
    )

    override fun write(value: Descriptors, buf: ByteBuffer) {
            FfiConverterString.write(value.`spendDescriptor`, buf)
            FfiConverterString.write(value.`watchDescriptor`, buf)
    }
}




data class KeyPair (
    var `secretKey`: String, 
    var `publicKey`: String
) {
    
}

public object FfiConverterTypeKeyPair: FfiConverterRustBuffer<KeyPair> {
    override fun read(buf: ByteBuffer): KeyPair {
        return KeyPair(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: KeyPair) = (
            FfiConverterString.allocationSize(value.`secretKey`) +
            FfiConverterString.allocationSize(value.`publicKey`)
    )

    override fun write(value: KeyPair, buf: ByteBuffer) {
            FfiConverterString.write(value.`secretKey`, buf)
            FfiConverterString.write(value.`publicKey`, buf)
    }
}




data class Tx (
    var `id`: String, 
    var `blob`: List<UByte>, 
    var `onChainFeeSat`: ULong, 
    var `outputSat`: ULong
) {
    
}

public object FfiConverterTypeTx: FfiConverterRustBuffer<Tx> {
    override fun read(buf: ByteBuffer): Tx {
        return Tx(
            FfiConverterString.read(buf),
            FfiConverterSequenceUByte.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: Tx) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterSequenceUByte.allocationSize(value.`blob`) +
            FfiConverterULong.allocationSize(value.`onChainFeeSat`) +
            FfiConverterULong.allocationSize(value.`outputSat`)
    )

    override fun write(value: Tx, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterSequenceUByte.write(value.`blob`, buf)
            FfiConverterULong.write(value.`onChainFeeSat`, buf)
            FfiConverterULong.write(value.`outputSat`, buf)
    }
}




data class TxDetails (
    var `id`: String, 
    var `outputAddress`: String, 
    var `outputSat`: ULong, 
    var `onChainFeeSat`: ULong, 
    var `status`: TxStatus
) {
    
}

public object FfiConverterTypeTxDetails: FfiConverterRustBuffer<TxDetails> {
    override fun read(buf: ByteBuffer): TxDetails {
        return TxDetails(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterTypeTxStatus.read(buf),
        )
    }

    override fun allocationSize(value: TxDetails) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`outputAddress`) +
            FfiConverterULong.allocationSize(value.`outputSat`) +
            FfiConverterULong.allocationSize(value.`onChainFeeSat`) +
            FfiConverterTypeTxStatus.allocationSize(value.`status`)
    )

    override fun write(value: TxDetails, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`outputAddress`, buf)
            FfiConverterULong.write(value.`outputSat`, buf)
            FfiConverterULong.write(value.`onChainFeeSat`, buf)
            FfiConverterTypeTxStatus.write(value.`status`, buf)
    }
}




data class WalletKeys (
    var `walletKeypair`: KeyPair, 
    var `walletDescriptors`: Descriptors
) {
    
}

public object FfiConverterTypeWalletKeys: FfiConverterRustBuffer<WalletKeys> {
    override fun read(buf: ByteBuffer): WalletKeys {
        return WalletKeys(
            FfiConverterTypeKeyPair.read(buf),
            FfiConverterTypeDescriptors.read(buf),
        )
    }

    override fun allocationSize(value: WalletKeys) = (
            FfiConverterTypeKeyPair.allocationSize(value.`walletKeypair`) +
            FfiConverterTypeDescriptors.allocationSize(value.`walletDescriptors`)
    )

    override fun write(value: WalletKeys, buf: ByteBuffer) {
            FfiConverterTypeKeyPair.write(value.`walletKeypair`, buf)
            FfiConverterTypeDescriptors.write(value.`walletDescriptors`, buf)
    }
}




enum class AuthLevel {
    PSEUDONYMOUS,OWNER,EMPLOYEE;
}

public object FfiConverterTypeAuthLevel: FfiConverterRustBuffer<AuthLevel> {
    override fun read(buf: ByteBuffer) = try {
        AuthLevel.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: AuthLevel) = 4

    override fun write(value: AuthLevel, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class AuthRuntimeErrorCode {
    AUTH_SERVICE_ERROR,ACCESS_EXPIRED,NETWORK_ERROR,GENERIC_ERROR,CORRUPT_DATA,OBJECT_NOT_FOUND;
}

public object FfiConverterTypeAuthRuntimeErrorCode: FfiConverterRustBuffer<AuthRuntimeErrorCode> {
    override fun read(buf: ByteBuffer) = try {
        AuthRuntimeErrorCode.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: AuthRuntimeErrorCode) = 4

    override fun write(value: AuthRuntimeErrorCode, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class LogLevel {
    ERROR,WARN,INFO,DEBUG,TRACE;
}

public object FfiConverterTypeLogLevel: FfiConverterRustBuffer<LogLevel> {
    override fun read(buf: ByteBuffer) = try {
        LogLevel.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: LogLevel) = 4

    override fun write(value: LogLevel, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class Network {
    BITCOIN,TESTNET,SIGNET,REGTEST;
}

public object FfiConverterTypeNetwork: FfiConverterRustBuffer<Network> {
    override fun read(buf: ByteBuffer) = try {
        Network.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Network) = 4

    override fun write(value: Network, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






sealed class TxStatus {
    object NotInMempool : TxStatus()
    
    object InMempool : TxStatus()
    
    data class Confirmed(
        val `numberOfBlocks`: UInt, 
        val `confirmedAt`: java.time.Instant
        ) : TxStatus()
    

    
}

public object FfiConverterTypeTxStatus : FfiConverterRustBuffer<TxStatus>{
    override fun read(buf: ByteBuffer): TxStatus {
        return when(buf.getInt()) {
            1 -> TxStatus.NotInMempool
            2 -> TxStatus.InMempool
            3 -> TxStatus.Confirmed(
                FfiConverterUInt.read(buf),
                FfiConverterTimestamp.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: TxStatus) = when(value) {
        is TxStatus.NotInMempool -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is TxStatus.InMempool -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is TxStatus.Confirmed -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterUInt.allocationSize(value.`numberOfBlocks`)
                + FfiConverterTimestamp.allocationSize(value.`confirmedAt`)
            )
        }
    }

    override fun write(value: TxStatus, buf: ByteBuffer) {
        when(value) {
            is TxStatus.NotInMempool -> {
                buf.putInt(1)
                Unit
            }
            is TxStatus.InMempool -> {
                buf.putInt(2)
                Unit
            }
            is TxStatus.Confirmed -> {
                buf.putInt(3)
                FfiConverterUInt.write(value.`numberOfBlocks`, buf)
                FfiConverterTimestamp.write(value.`confirmedAt`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






enum class WalletRuntimeErrorCode {
    ELECTRUM_SERVICE_UNAVAILABLE,NOT_ENOUGH_FUNDS,REMOTE_SERVICE_UNAVAILABLE,SEND_TO_OURSELVES,GENERIC_ERROR;
}

public object FfiConverterTypeWalletRuntimeErrorCode: FfiConverterRustBuffer<WalletRuntimeErrorCode> {
    override fun read(buf: ByteBuffer) = try {
        WalletRuntimeErrorCode.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: WalletRuntimeErrorCode) = 4

    override fun write(value: WalletRuntimeErrorCode, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







sealed class AddressParsingException: Exception() {
    // Each variant is a nested class
    
    class InvalidNetwork(
        val `expected`: Network, 
        val `address`: Network
        ) : AddressParsingException() {
        override val message
            get() = "expected=${ `expected` }, address=${ `address` }"
    }
    
    class Other(
        ) : AddressParsingException() {
        override val message
            get() = ""
    }
    

    companion object ErrorHandler : CallStatusErrorHandler<AddressParsingException> {
        override fun lift(error_buf: RustBuffer.ByValue): AddressParsingException = FfiConverterTypeAddressParsingError.lift(error_buf)
    }

    
}

public object FfiConverterTypeAddressParsingError : FfiConverterRustBuffer<AddressParsingException> {
    override fun read(buf: ByteBuffer): AddressParsingException {
        

        return when(buf.getInt()) {
            1 -> AddressParsingException.InvalidNetwork(
                FfiConverterTypeNetwork.read(buf),
                FfiConverterTypeNetwork.read(buf),
                )
            2 -> AddressParsingException.Other()
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: AddressParsingException): Int {
        return when(value) {
            is AddressParsingException.InvalidNetwork -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
                + FfiConverterTypeNetwork.allocationSize(value.`expected`)
                + FfiConverterTypeNetwork.allocationSize(value.`address`)
            )
            is AddressParsingException.Other -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
            )
        }
    }

    override fun write(value: AddressParsingException, buf: ByteBuffer) {
        when(value) {
            is AddressParsingException.InvalidNetwork -> {
                buf.putInt(1)
                FfiConverterTypeNetwork.write(value.`expected`, buf)
                FfiConverterTypeNetwork.write(value.`address`, buf)
                Unit
            }
            is AddressParsingException.Other -> {
                buf.putInt(2)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class AuthException: Exception() {
    // Each variant is a nested class
    
    class InvalidInput(
        val `msg`: String
        ) : AuthException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class RuntimeException(
        val `code`: AuthRuntimeErrorCode, 
        val `msg`: String
        ) : AuthException() {
        override val message
            get() = "code=${ `code` }, msg=${ `msg` }"
    }
    
    class PermanentFailure(
        val `msg`: String
        ) : AuthException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    

    companion object ErrorHandler : CallStatusErrorHandler<AuthException> {
        override fun lift(error_buf: RustBuffer.ByValue): AuthException = FfiConverterTypeAuthError.lift(error_buf)
    }

    
}

public object FfiConverterTypeAuthError : FfiConverterRustBuffer<AuthException> {
    override fun read(buf: ByteBuffer): AuthException {
        

        return when(buf.getInt()) {
            1 -> AuthException.InvalidInput(
                FfiConverterString.read(buf),
                )
            2 -> AuthException.RuntimeException(
                FfiConverterTypeAuthRuntimeErrorCode.read(buf),
                FfiConverterString.read(buf),
                )
            3 -> AuthException.PermanentFailure(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: AuthException): Int {
        return when(value) {
            is AuthException.InvalidInput -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is AuthException.RuntimeException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
                + FfiConverterTypeAuthRuntimeErrorCode.allocationSize(value.`code`)
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is AuthException.PermanentFailure -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
                + FfiConverterString.allocationSize(value.`msg`)
            )
        }
    }

    override fun write(value: AuthException, buf: ByteBuffer) {
        when(value) {
            is AuthException.InvalidInput -> {
                buf.putInt(1)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is AuthException.RuntimeException -> {
                buf.putInt(2)
                FfiConverterTypeAuthRuntimeErrorCode.write(value.`code`, buf)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is AuthException.PermanentFailure -> {
                buf.putInt(3)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class WalletException: Exception() {
    // Each variant is a nested class
    
    class InvalidInput(
        val `msg`: String
        ) : WalletException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class RuntimeException(
        val `code`: WalletRuntimeErrorCode, 
        val `msg`: String
        ) : WalletException() {
        override val message
            get() = "code=${ `code` }, msg=${ `msg` }"
    }
    
    class PermanentFailure(
        val `msg`: String
        ) : WalletException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    

    companion object ErrorHandler : CallStatusErrorHandler<WalletException> {
        override fun lift(error_buf: RustBuffer.ByValue): WalletException = FfiConverterTypeWalletError.lift(error_buf)
    }

    
}

public object FfiConverterTypeWalletError : FfiConverterRustBuffer<WalletException> {
    override fun read(buf: ByteBuffer): WalletException {
        

        return when(buf.getInt()) {
            1 -> WalletException.InvalidInput(
                FfiConverterString.read(buf),
                )
            2 -> WalletException.RuntimeException(
                FfiConverterTypeWalletRuntimeErrorCode.read(buf),
                FfiConverterString.read(buf),
                )
            3 -> WalletException.PermanentFailure(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: WalletException): Int {
        return when(value) {
            is WalletException.InvalidInput -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is WalletException.RuntimeException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
                + FfiConverterTypeWalletRuntimeErrorCode.allocationSize(value.`code`)
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is WalletException.PermanentFailure -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
                + FfiConverterString.allocationSize(value.`msg`)
            )
        }
    }

    override fun write(value: WalletException, buf: ByteBuffer) {
        when(value) {
            is WalletException.InvalidInput -> {
                buf.putInt(1)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is WalletException.RuntimeException -> {
                buf.putInt(2)
                FfiConverterTypeWalletRuntimeErrorCode.write(value.`code`, buf)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is WalletException.PermanentFailure -> {
                buf.putInt(3)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




public object FfiConverterOptionalString: FfiConverterRustBuffer<String?> {
    override fun read(buf: ByteBuffer): String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: String?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




public object FfiConverterSequenceUByte: FfiConverterRustBuffer<List<UByte>> {
    override fun read(buf: ByteBuffer): List<UByte> {
        val len = buf.getInt()
        return List<UByte>(len) {
            FfiConverterUByte.read(buf)
        }
    }

    override fun allocationSize(value: List<UByte>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterUByte.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<UByte>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterUByte.write(it, buf)
        }
    }
}




public object FfiConverterSequenceString: FfiConverterRustBuffer<List<String>> {
    override fun read(buf: ByteBuffer): List<String> {
        val len = buf.getInt()
        return List<String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<String>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




public object FfiConverterSequenceTypeTxDetails: FfiConverterRustBuffer<List<TxDetails>> {
    override fun read(buf: ByteBuffer): List<TxDetails> {
        val len = buf.getInt()
        return List<TxDetails>(len) {
            FfiConverterTypeTxDetails.read(buf)
        }
    }

    override fun allocationSize(value: List<TxDetails>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterTypeTxDetails.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<TxDetails>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterTypeTxDetails.write(it, buf)
        }
    }
}

fun `initNativeLoggerOnce`(`minLevel`: LogLevel) =
    
    rustCall() { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_init_native_logger_once(FfiConverterTypeLogLevel.lower(`minLevel`), _status)
}

@Throws(WalletException::class)

fun `generateMnemonic`(): List<String> {
    return FfiConverterSequenceString.lift(
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_generate_mnemonic( _status)
})
}


@Throws(WalletException::class)

fun `deriveKeys`(`network`: Network, `mnemonicString`: List<String>): WalletKeys {
    return FfiConverterTypeWalletKeys.lift(
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_derive_keys(FfiConverterTypeNetwork.lower(`network`), FfiConverterSequenceString.lower(`mnemonicString`), _status)
})
}


@Throws(WalletException::class)

fun `sign`(`message`: String, `privateKey`: String): String {
    return FfiConverterString.lift(
    rustCallWithError(WalletException) { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_sign(FfiConverterString.lower(`message`), FfiConverterString.lower(`privateKey`), _status)
})
}



fun `generateKeypair`(): KeyPair {
    return FfiConverterTypeKeyPair.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.lipabusinesslib_f273_generate_keypair( _status)
})
}




